#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
    sort_translit = true
    linemode = "size_and_mtime"
    show_hidden = true
    show_symlink = false
    title_format = "{cwd}"

[preview]
    wrap = "yes"
    tab_size = 4

[input]
    cursor_blink = true

[which]
    sort_by = "key"
    sort_translit = true
