'$schema' = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](red)\
$sudo\
[](fg:red bg:peach)\
$hostname\
$directory\
[](peach)\
$fill\
[](green)\
$status\
$jobs\
$cmd_duration\
[](fg:lavender bg:green)\
$time\
[▓▒░](lavender)\
$line_break\
$character"""

palette = 'sphs'
add_newline = false
continuation_prompt = '[▹▸ ](dimmed green)'

# Modules

[sudo]
disabled = false
symbol = '󱐋'
style = 'fg:crust bg:red'
format = '[ $symbol]($style)'

[hostname]
ssh_symbol = ""
style = 'fg:crust bg:peach'
format = '[ $ssh_symbol $hostname ]($style)'

[directory]
read_only = ""
style = 'fg:crust bg:peach'
read_only_style = 'fg:crust bg:peach'
format = '[( $read_only)]($read_only_style)[ $path]($style)'
truncation_length = 3
truncation_symbol = '…/'

[directory.substitutions]
'Documents' = '󰈙 '
'Downloads' = ' '
'Music' = '󰝚 '
'Pictures' = ' '
'Developer' = '󰲋 '

[fill]
symbol = ' '

[status]
disabled = false
style = 'fg:crust bg:green'
format = '[$symbol\[$status\] ]($style)'

[jobs]
symbol = '󰫢'
style = 'fg:crust bg:green'
format = '[$symbol $number ]($style)'
number_threshold = 1

[cmd_duration]
disabled = false
style = 'fg:crust bg:green'
format = '[ $duration ]($style)'
show_milliseconds = true
show_notifications = false
min_time = 500
min_time_to_notify = 50000

[time]
disabled = false
time_format = '%r'
style = 'fg:crust bg:lavender'
format = '[$time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[󱞫](bold fg:green)'
error_symbol = '[󱞫](bold fg:red)'

# Palettes

[palettes.sphs]
rosewater = '#f4dbd6'
flamingo = '#f0c6c6'
pink = '#f5bde6'
mauve = '#c6a0f6'
red = '#ed8796'
maroon = '#ee99a0'
peach = '#f5a97f'
yellow = '#eed49f'
green = '#a6da95'
teal = '#8bd5ca'
sky = '#91d7e3'
sapphire = '#7dc4e4'
blue = '#8aadf4'
lavender = '#b7bdf8'
text = '#cad3f5'
subtext1 = '#b8c0e0'
subtext0 = '#a5adcb'
overlay2 = '#939ab7'
overlay1 = '#8087a2'
overlay0 = '#6e738d'
surface2 = '#5b6078'
surface1 = '#494d64'
surface0 = '#363a4f'
base = '#24273a'
mantle = '#1e2030'
crust = '#181926'
